version: '3'

services:
  db:
    image: mysql:8
    container_name: example-db
    volumes:
      - db_volume:/var/lib/mysql
    ports:
      - '7777:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
volumes:
  db_volume:
